- name: Python-apt package installation.
  shell: "/usr/bin/apt -y install python-apt"

- name: Apt supplemental packages installation
  apt:
    name: "{{item}}"
    state: latest
    install_recommends: no
    update_cache: yes
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "python-psutil"

- name: Checking installdir existence
  stat:
    path: "{{primary_install_path}}"
  register: installdir

- name: Creating installdir if not exists
  file:
    path: "{{primary_install_path}}"
    state: directory
  when: installdir.stat.exists == False

- name: Uploading microservice
  copy:
    src: "{{server_file}}"
    dest: "{{primary_install_path}}/{{server_file}}"
    owner: root
    group: root
    mode: 0755

- name: Creating systemd .service file for microservice
  template:
    src: "{{server_file}}.service.j2"
    dest: /etc/systemd/system/{{server_file}}.service
    owner: root
    group: root
    mode: 0600

- name: Starting server on localhost 8080
  systemd:
    name: "{{server_file}}"
    state: started
    enabled: yes
    daemon-reload: yes
