- name: Installing web server support packages
  apt:
    name: "{{item}}"
    state: latest
    install_recommends: no
  with_items:
    - "nginx-light"
    - "python-ndg-httpsclient"

- name: Removing default site
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-available/default"

- name: Creating basic nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0600

- name: Creating proxy config
  template:
    src: "proxy.j2"
    dest: "/etc/nginx/sites-available/proxy"
    owner: root
    group: root
    mode: 0600

- name: Creating OpenSSL key
  openssl_privatekey:
    path: /etc/nginx/{{server_file}}.key

- name: Creating certificate request (CSR)
  openssl_csr:
    path: /etc/nginx/{{server_file}}.csr
    privatekey_path: /etc/nginx/{{server_file}}.key
    country_name: RU
    organization_name: Horns and Hoofs
    email_address: jdoe@a.b
    common_name: example.com

- name: Generating a self signed OpenSSL certificate
  openssl_certificate:
    path: /etc/nginx/{{server_file}}.crt
    privatekey_path: /etc/nginx/{{server_file}}.key
    csr_path: /etc/nginx/{{server_file}}.csr
    provider: selfsigned
    valid_in: 1209600

- name: Enabling nginx http proxy
  file:
    src: "/etc/nginx/sites-available/proxy"
    dest: "/etc/nginx/sites-enabled/proxy"
    state: link

